### PR TITLE
DOC-5969 update sslmode for npgsql

### PR DESCRIPTION
**Pull request by andf-crl**
Addresses: [DOC-5969](https://cockroachlabs.atlassian.net/browse/DOC-5969)

Hi Eric! This is the `hello-world-csharp` side of https://github.com/cockroachdb/docs/pull/16101, spawned by Artem's [DOC-5969](https://cockroachlabs.atlassian.net/browse/DOC-5969). Please reach out to Artem if his suggestion discounts context unknown! 

Or let me know if there's more to be done in `hello-world-csharp` to accommodate this. Thanks much for the help!

### CODE REVIEW

**Review by ericharmeling — APPROVED** [review]
If you've tested this out and it runs just fine, then LGTM! I'd have Artem review these example changes though (I am not a C# expert).

**Comment by andf-crl** [comment]
Thanks Eric. I'll work with Artem. Appreciate the quick review!

**Comment by dbist** [comment]
LGTM, I just tested with those two changes and it works.

**Review by dbist — APPROVED** [review]
LGTM

**Comment by andf-crl** [comment]
Thanks both!! I'll get this live.

**Pull request merged**
